### ISSUE TITLE
request enable COPR builds for f35/rawhide

### ISSUE THREAD

**Issue by pgnd** [ZaWertun/fedora-copr-hack-fonts#1]
with F35 around the corner, could you enable repo builds @

https://copr.fedorainfracloud.org/coprs/zawertun/hack-fonts

for F35 & rawhide?

still the most convenient install method for Hack.

thx!

**Comment by ZaWertun** [comment]
Sure thing. Just wait a while.

**Comment by ZaWertun** [comment]
fedora-35: https://copr.fedorainfracloud.org/coprs/zawertun/hack-fonts/build/2830950/
fedora-rawhide: https://copr.fedorainfracloud.org/coprs/zawertun/hack-fonts/build/2830953/

**Comment by ZaWertun** [comment]
One build for rawhide has failed, started new one: https://copr.fedorainfracloud.org/coprs/zawertun/hack-fonts/build/2830954/.
